version: '3.3'

services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        ports:
            - 80:80
        networks:
            - network

    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www/html
            - ./docker/php-fpm/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        depends_on:
            - mysql
            - mysql-test
        user: '${USER_ID:-1000}:${GROUP_ID:-1000}'
        environment:
            MYSQL_HOST: 'mysql:3306'
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
        networks:
            - network

    mysql:
        image: mysql:8
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
        ports:
            - 33061:3306
        command: --innodb_use_native_aio=0
        networks:
            - network

    mysql-test:
        image: mysql:8
        volumes:
            - mysql-test:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
        ports:
            - 33062:3306
        command: --innodb_use_native_aio=0
        networks:
            - network

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - network

networks:
    network:
        driver: bridge
volumes:
    mysql:
        driver: local
    mysql-test:
        driver: local